# -*- coding: utf-8 -*-
"""psd1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBrtE8keqjEKGPO9OVnQfa0vag_xWvEN
"""

import pandas as pd
import numpy as np

# 1. Load data dari CSV di GitHub (raw link)
url = 'https://raw.githubusercontent.com/yourcen12/psd/main/kinerja_pegawai.csv'
data = pd.read_csv(url)

print(data)

data_kategori = data.select_dtypes(include=['object'])
kategori_encoded = pd.get_dummies(data_kategori, drop_first=False)
data_encoded = kategori_encoded.astype(int)

data_encoded

# Menghitung mean, median, dan mode untuk kolom 'age'
mean_age = data['age'].mean()
median_age = data['age'].median()
mode_age = data['age'].mode()[0]

print(f"Mean umur: {mean_age}")
print(f"Median umur: {median_age}")
print(f"Modus umur: {mode_age}")

data_numerik = data.select_dtypes(include=['number'])
range_data = data_numerik.max() - data_numerik.min()
variance = data_numerik.var()
std_dev = data_numerik.std()

print("Range untuk kolom numerik :")
print(range_data)

print("\nVariance untuk kolom numerik :")
print(variance)

print("\nStandard Deviation :")
print(std_dev)